import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const outfitFont = Outfit({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${outfitFont.className} h-full antialiased`}
    >
      <body className="">
        <Navbar></Navbar>
        <main className="">
          {children}
        </main>
        <Footer></Footer>
        <ToastContainer 
          position="top-right"
          autoClose={3000}
          theme="light" 
        />


        </body>
    </html>
  );
}
